export const images = {
  aerobics: require('./Gym/aerobics.svg'),
  box: require('./Gym/box.svg'),
  children_selection: require('./Gym/children_selection.svg'),
  dances: require('./Gym/dances.svg'),
  dumbbell: require('./Gym/dumbbell.svg'),
  favorite_selected: require('./Gym/favorite_selected.svg'),
  yoga: require('./Gym/yoga.svg'),
  wrestling: require('./Gym/wrestling.svg'),
  swimming: require('./Gym/swimming.svg'),
  run: require('./Gym/run.svg'),
  search: require('./Gym/search.svg'),
  map: require('./Gym/map.svg'),
  location: require('./Gym/location.svg'),
  gym_rebel: require('./Gym/gym_rebel.svg'),
  watch: require('./Gym/watch.svg'),
  favorite: require('./Gym/favorite.svg'),
  gym_non_stop: require('./Gym/gym_non_stop.svg'),
};
